### PR TITLE
do not insert after null in table

### LINKED ISSUE #53: `AttributeError: 'Null' object has no attribute '_trivia'` after removing elements from table.
Code:

```python
...  # removing many of the keys except the first in the table
table['test'] = 1
```

Traceback:

```python
  File "/home/gram/.local/lib/python3.6/site-packages/tomlkit/container.py", line 528, in __setitem__
    self.append(key, value)
  File "/home/gram/.local/lib/python3.6/site-packages/tomlkit/container.py", line 175, in append
    return self._insert_at(key_after + 1, key, item)
  File "/home/gram/.local/lib/python3.6/site-packages/tomlkit/container.py", line 292, in _insert_at
    and "\n" not in previous_item.trivia.trail
  File "/home/gram/.local/lib/python3.6/site-packages/tomlkit/items.py", line 237, in trivia
    return self._trivia
AttributeError: 'Null' object has no attribute '_trivia'
```

Troubles somewhere in this cycle:
https://github.com/sdispater/tomlkit/blob/master/tomlkit/container.py#L156-L170

After this block execution `idx` points on `Null` that should be avoided.

However, I haven't found where is the exact error.

Locals inside `Container.append`:

```python
{'idx': 3, 'key_after': 2, 'is_table': False, 'v': <Whitespace '\n'>, 'k': None, 'item': {'path': '/home/gram/Documents/dephell/tests/requirements/sdist.tar.gz', 'version': '*'}, 'key': <Key test>, 'self': {'python': '==3.5'}, '__class__': <class 'tomlkit.container.Container'>}
```

`self._body`:

```python
(<Key python>, '==3.5')
(None, <tomlkit.items.Null object at 0x7fb1130380b8>)
(None, <tomlkit.items.Null object at 0x7fb113038be0>)
(None, <tomlkit.items.Null object at 0x7fb113038dd8>)
(None, <tomlkit.items.Null object at 0x7fb113038eb8>)
(None, <tomlkit.items.Null object at 0x7fb113038f98>)
(None, <tomlkit.items.Null object at 0x7fb1130385c0>)
(None, <tomlkit.items.Null object at 0x7fb113000048>)
(None, <tomlkit.items.Null object at 0x7fb113000668>)
(None, <tomlkit.items.Null object at 0x7fb1130005f8>)
(None, <tomlkit.items.Null object at 0x7fb113000828>)
(None, <tomlkit.items.Null object at 0x7fb1130007f0>)
(None, <tomlkit.items.Null object at 0x7fb1130008d0>)
(None, <tomlkit.items.Null object at 0x7fb1130002b0>)
(None, <tomlkit.items.Null object at 0x7fb113003128>)
(None, <tomlkit.items.Null object at 0x7fb1130030b8>)
(None, <tomlkit.items.Null object at 0x7fb113003278>)
(None, <tomlkit.items.Null object at 0x7fb113003390>)
(None, <tomlkit.items.Null object at 0x7fb113003320>)
(None, <tomlkit.items.Null object at 0x7fb1130034a8>)
(None, <tomlkit.items.Null object at 0x7fb1130035f8>)
(None, <Whitespace '\n'>)
(None, <tomlkit.items.Comment object at 0x7fb113003860>)
(None, <tomlkit.items.Null object at 0x7fb113003710>)
(None, <tomlkit.items.Null object at 0x7fb1130036a0>)
(None, <tomlkit.items.Null object at 0x7fb113003780>)
(None, <tomlkit.items.Null object at 0x7fb113003908>)
(None, <tomlkit.items.Null object at 0x7fb113003b38>)
(None, <Whitespace '\n'>)
(None, <tomlkit.items.Comment object at 0x7fb113006588>)
(None, <tomlkit.items.Null object at 0x7fb113003fd0>)
(None, <tomlkit.items.Null object at 0x7fb113003d68>)
(None, <tomlkit.items.Null object at 0x7fb113003b00>)
(None, <tomlkit.items.Null object at 0x7fb1130038d0>)
(None, <tomlkit.items.Null object at 0x7fb113003748>)
(None, <tomlkit.items.Null object at 0x7fb113003668>)
(None, <tomlkit.items.Null object at 0x7fb113003588>)
(None, <tomlkit.items.Null object at 0x7fb1130034e0>)
(None, <tomlkit.items.Null object at 0x7fb1130033c8>)
(None, <tomlkit.items.Null object at 0x7fb1130032e8>)
(None, <Whitespace '\n'>)
```

`v` points on the latest element in the body. So, `break` hasn't been called.

:thinking:

### PR DESCRIPTION
**Pull request by orsinium**
Fixes #53

### CODE REVIEW

**Comment by orsinium** [comment]
Failed build unrelated:
https://travis-ci.com/sdispater/tomlkit/jobs/216533147

**Comment by orsinium** [comment]
Bum! I've added a test case that reproduces the bug.

**Comment by orsinium** [comment]
Black is fixed, now Travis should be satisfied.

Coverage degradation because of removing some lines that were covered. Removing code to fix a bug is always cool :)

**Comment by orsinium** [comment]
Oh, I forgot about this bug.

@sdispater, please, take care of poetry for pypy:
https://travis-ci.com/sdispater/tomlkit/jobs/219079234

**Comment by orsinium** [comment]
@sdispater it is ready for review (and to be merged). About coverage degradation:
https://github.com/sdispater/tomlkit/pull/54#issuecomment-514594949

**Comment by frostming** [comment]
Already fixed in the master

**Pull request closed without merging**
