### PR TITLE
Cleanup CI for Python 3.11 support

### PR DESCRIPTION
**Pull request by Secrus**
As in title.

### CODE REVIEW

**Comment by Secrus** [comment]
@frostming are you open to dropping Python 3.6 now?

**Comment by frostming** [comment]
> @frostming are you open to dropping Python 3.6 now?

Okay for a minor release (0.12.0), can you help do it?

**Comment by Secrus** [comment]
> > @frostming are you open to dropping Python 3.6 now?
> 
> Okay for a minor release (0.12.0), can you help do it?

Sure, I will take care of it.

**Comment by Secrus** [comment]
@frostming #252

**Pull request merged**
